# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zhmakeindex < Formula
  desc "Chinese-aware makeindex replacement for LaTeX"
  homepage "https://github.com/Liam0205/zhmakeindex"
  version "1.2.1-rc3"
  license "LPPL-1.3c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc3/zhmakeindex_1.2.1-rc3_darwin_amd64.tar.gz"
      sha256 "9f71d1d0289defc1db42a43fe92f6086741dff9274e62e4c5849a0e8536bdd48"

      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc3/zhmakeindex_1.2.1-rc3_darwin_arm64.tar.gz"
      sha256 "e8b36346f80be15537567e8bd78f719b2d5ccecf7714822d299f4299d4977286"

      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc3/zhmakeindex_1.2.1-rc3_linux_amd64.tar.gz"
      sha256 "ffa8f86f0cbc9b6f9e2e47dd84866a9e4275c6bc5e1c7654a97e32771073c5a0"
      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc3/zhmakeindex_1.2.1-rc3_linux_arm64.tar.gz"
      sha256 "d7a563a1c20651859173af0f7eef372ddefc47089577bc0b4627f836e45f2b54"
      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
  end

  test do
    assert_match "zhmakeindex", shell_output("#{bin}/zhmakeindex 2>&1", 0)
  end
end
