# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zhmakeindex < Formula
  desc "Chinese-aware makeindex replacement for LaTeX"
  homepage "https://github.com/Liam0205/zhmakeindex"
  version "1.2.1-rc.1"
  license "LPPL-1.3c"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc.1/zhmakeindex_1.2.1-rc.1_darwin_amd64.tar.gz"
      sha256 "b83ff7c54ca288afad8dbeed2e81aea9868abfe0efca925f28eeed03fe5767af"

      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc.1/zhmakeindex_1.2.1-rc.1_darwin_arm64.tar.gz"
      sha256 "4cdcf0ccb59f9e783a4a5abb3534b144bcbb5daba70e19c43019c4e6d342c57d"

      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc.1/zhmakeindex_1.2.1-rc.1_linux_amd64.tar.gz"
      sha256 "c8acd4636b6c2f74d4a27168468f7579be1739b922846df6339ba641ef741415"
      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Liam0205/zhmakeindex/releases/download/v1.2.1-rc.1/zhmakeindex_1.2.1-rc.1_linux_arm64.tar.gz"
      sha256 "7f12f93864946f2bfc5769b48fcd0e2b39e79524c014ddca7dd79468ea3940be"
      define_method(:install) do
        bin.install "zhmakeindex"
      end
    end
  end

  test do
    assert_match "zhmakeindex", shell_output("#{bin}/zhmakeindex 2>&1", 0)
  end
end
